name: ci

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  TestMatrix:
    strategy:
      fail-fast: false
      matrix:
        lua-version: [ "5.5", "5.4", "5.3", "5.2", "5.1", "luajit" ]
        libflag: ["-shared --coverage"]
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@main

      - name: Install Lua
        uses: luarocks/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.lua-version }}

      - name: Install Luarocks
        uses: luarocks/gh-actions-luarocks@master

      - name: Install dependencies
        run: |
          luarocks install lpeglabel
          luarocks install luacov

      - name: Run tests
        run: |
          lua -lluacov test.lua
